apiVersion: v1
kind: Pod
metadata:
  name: only-sidecave
  namespace: k8s-exploration
spec:
  containers:
    # This is an image created via `docker build -t sidecave ./sidecave`
  - name: sidecave
    image: sidecave
    imagePullPolicy: IfNotPresent
